version: '3'
services:
  backend:
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
  frontend:
    build:
      context: ./react-frontend
      dockerfile: ./Dockerfile
    ports:
      - "3000:80"
  frontend-angular:
    build:
      context: ./angular-frontend
      dockerfile: ./Dockerfile
    ports:
      - "4000:80"
